[package]
name = "cellbook-macros"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "cellbook_macros"
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.106", features = ["span-locations"] }
quote = "1.0.44"
syn = { version = "2.0.114", features = ["full"] }
