[workspace]
default-members = []
exclude = []
members = ["cargo-cellbook", "cellbook", "cellbook-macros", "examples/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
