[package]
edition = "2021"
name = "cellbook"
version = "0.0.0"

[lib]
name = "cellbook"
path = "src/lib.rs"

[dependencies]
cellbook-macros = { path = "../cellbook-macros" }
futures = "0.3"
inventory = "0.3"
parking_lot = "0.12"
thiserror = "2.0.17"
