[package]
edition = "2021"
name = "context-demo"
version = "0.0.0"

[[bin]]
name = "context-demo"
path = "cellbook.rs"

[dependencies]
cellbook = { path = "../../cellbook" }
tokio = { version = "1", features = ["full"] }
