[package]
edition = "2021"
name = "plot-timeseries"
version = "0.1.0"

[[bin]]
name = "plot-timeseries"
path = "cellbook.rs"

[dependencies]
cellbook = { path = "../../cellbook" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
